var loves = [" I love you and I'm glad that ya'll are by my side through this whole thing",
" I love you Jennifer, mom, Jaime, Cory, David",
" Support and love each other",
" I love you",
" I love you",
" I love you Mandy, Tiffany",
" I love you, too",
" Thanks for being with me and all of your love",
" I appreciate the people that helped me out, and uh, know that I love you, Angel and your family and all the people that helped me out",
" I love you",
" I love ya'll",
" To my friends and my loved ones, Miriam, I love you, thanks for being here for me",
" Yes, I would like to tell my wife that I love her and thank her for all the years of happiness",
" I just want to say I don't want you to have hate in your heart for me, because I took your loved one",
" I know it doesn't mean anything; I told the truth because I feel like you should know who killed your loved one",
" I'm sorry for taking your loved one",
" I love ya'll",
" I love everyone that loves me",
" I ain't got no love for anyone that don't love me",
" To my family, I love ya'll",
" To my loved ones and dear friends, I love ya'll and appreciate ya'll for being there",
" I love ya'll; Sheena, my sister, momma, and daddy",
" I love ya'll and thank you for the love you gave me",
" I love ya'll, all of you people in there",
" Terella, I feel it babe, love",
" Mom, Celeste: Please know I'm innocent and I love you both",
" I love you",
" Give everybody my love",
" I love all of you",
" Tell everyone I love them",
" I love them all; tell mom, everybody",
" Tell Brenda I love her",
" I loved your daughter",
" I love both of ya'll",
" Please tell my daughter I love her",
" I love my family",
" I love everybody",
" I have love in my heart for ya'll and for my family, we're all victims behind what I did",
" I love ya'll",
" I love ya'll",
" Yes, you know I sat in my cell many days wondering what my last words would be: love for my family, grandson, friends",
" I love you very much",
" Over the years I have learned to love",
" I love you so, Susan",
" You know what it is girl, love ya",
" Much love to you all",
" Cox, love you",
" She showed God's love for letting me know that love will be there to welcome me home",
" I love you all",
" I love you",
" I love you all: Susan, Mrs",
" I love you all",
" What a friend we have in Jesus, oh my God, I lay in awe 'cause I love you God",
" I love you momma",
" I love you Susan",
" I want to tell ya'll, know that I love you",
" Billy, I love you, English, Hart and Eloise",
"  I love ya'll",
" Yes, I would like to tell my family that I love ya'll and I wish ya'll well",
" Bohannon, Peg and Kim, I love ya'll",
" Give mom a hug for me and tell her that I love her",
" I love ya'll",
" I love each and every one of you",
" To my wife, I love you",
" I love each and every one of ya'll",
" I really love ya'll",
" Linda, I love you, I appreciate you",
" I love ya'll, be strong for me",
" Tell my son I love him very much",
" I love you so dearly",
" I love you so dearly",
" I love you",
" Yes, I want to tell everybody that I love everybody",
" Jung and Arthur, tell my family I love them",
" I love everybody",
" Tell Emmanuel and Joseph I love them",
" I love you, Mom",
" I love you, Tali",
" I love you too, Mom",
" I love you Israel",
" Spark, I love you, all of you",
" I love you Conna",
" I just want to say to all my supporters, family and friends; I love y'all and appreciate y'all",
" I love my family",
" I love you too, Mom",
" To everybody, know that I love you and I am OK",
" To my mom and everybody, I love you",
" Noel, I love you man",
" Jennifer, I love you",
" Mom, I love you",
" I love you, baby",
" I love you, Jennifer",
" Mom, I love you and all my friends that I have known over the years that have always been there for me",
" I love you, baby",
"   Yes, Tell my sister Tracey, I love you",
" Nicole, thank you and I love you",
" Wanda and all of my friends, I love you and thank you for your support",
" Mom, I love you",
" To my brothers and sisters and all my family members who have supported me and who have loved me despite my faults and imperfections",
" I hope it helps his family, son and loved ones",
" Please tell Robert and Eric, I love them",
" Tell your family I love them",
" Tell, everyone I love them",
" Give my love to the grandchildren",
" Tell Jake and Mia, Papa Alba loves them",
" Okay Warden, let's do it, I love yall",
" I love you Adonya",
" We need to love each other like we use to",
" Deena, Bob we were raised in the same house, we need to take care of each other and love each other like we use to",
" Adela I love you, Mijta, I need you to take care of your mom",
" We need to love each other like we use to",
" Thank you for showing me that I can be loved again",
" You showed me a love that I sometimes didn't deserve",
" I love you for that",
" I love you, I love you, I love you, I love you , I love you, I love you too bro",
" I love each and every one of you",
" I do know how it feels to have lost loved ones",
" This was the only way God could save me; I would pay it back a thousand times to bring back your loved ones",
" I love each and every one of you and hope you can find forgiveness for me",
" God's love is infinite",
" God loves me and God loves you",
"   Samantha, I love you with all my heart and soul",
" Yes I do, I would like to thank my family for their support, love and understanding",
" I love you man, I love you",
" I love you too Shay I love you if your listening I am sorry to be putting everybody through this",
" Danielle, you know that I love you",
" I love you little hef",
" For you love",
" I love you, love you too",
"  Yeah, I want to tell my family I love ya'll",
" Tell Kate I love her too",
" To my family, I love you, be strong",
" I love you sister",
" I love you all, please go and try and talk to the family",
" I love my family",
" Do not have any excuses for not extending your love",
" I love my family, I love you Jesus",
" Be strong mama, I love you sister",
" I love Jesus",
" Mom, Pa, Kristy, Khristopher, Tony I love all ya'll",
" I love each and everyone dearly",
" I love you",
" Yaws, Junie I love yall",
" And I love you",
" Amber I love you",
" I love you brother never forget it",
" I love you",
" But, I love you",
" Renee, I love you baby",
" I love you , I'm through with my statement",
"   No, I love you",
" I love my children, Roxanne, Roseanne, Melissa, and Louis",
" God loves everybody and myself",
"   Yes sir, I want to tell my mom that I love her and thank her for everything that she has done for me",
" Tell my sister that I love her too thank her for everything that she has done for me",
" I love you too",
" I love you too",
" I only have love in my heart",
" To my kids, Daddy loves you",
" We are filled with love looking for affection and a way to understand",
" We want pleasure love and satisfaction",
" Mija, I love you",
" I hope you find peace and know that I love you",
"   I love my family",
" I love you and my kids",
" Um Abel, Love ya'll, Evelyn love ya'll, Armando and Delia I love ya'll",
" I know ya'll love John Gomez but he was a violent man",
" John Gomez was there he told Veronica that \"he doesn't love you\" I didn't care",
" I love you Roxanne, Kaye",
" (After the official last statement ended, he said I love you Mom",
" I love you Irene and I want to thank you for all the beautiful years of friendship and ministry",
" I love you",
"   I love you all",
" Take comfort in each other, I love you all",
" I love you, Chantal",
" I love you, Zena",
" Tell Robin I love her, she is my one and only",
" I love you Chantal I love you baby",
" Barbara, I love you, Al and Paul, I love you",
" Jess and Chong, I love you now and forever",
" To my family, to my brother Gerard, I love you, Harold, I love you",
" To my step father Paul, I love you",
" Momma, I will always love you",
" Dad loves you",
" I love you mom",
" I love you all, take care",
" I love you too pop, keep your head up",
" I love ya'll, peace",
" I love my famly",
"   Laura, I love you, stay strong",
" I love you Laura",
" I love you Danny",
" I love you Irene",
" I appreciate everybody for their love and support",
" You all keep strong, thank you for showing me love and teaching me how to love",
" I love you all",
" I thank my family, loved ones, and friends",
" I love you Mary Taylor with all my heart, I always have",
" I love you, Michelle",
" I love all of you",
" To the Sanchez family who showed me love",
"  Yeah, I love all ya'll",
" I love you Edgardo; I appreciate your hard work",
" I love you",
" This doesn't solve anything, 'cause it hurts others that love me",
" I love you Kjersti",
" I love you too Roland",
" I love you too Uncle Kyle; I am still your nephew, no matter what you believe",
" I love you",
" I lovel you Angel, Let's ride",
" First of all I want to thank God for the love; thank God for the love from the family and friends that I have",
" I love and care about the Lord",
" Know that your loved one is in a good place",
" Francis, I love you and thank you for being here",
" I love you guys, I love you guys",
" I love you Chiquita",
" I just want to let you all know that I appreciate the love and support over the years",
" Same thing to all my pen friends and other friends, I love you all",
" Even though you don't know me, I love you, I love all of ya'll",
" To my family, I love all of you",
" I love my Father",
" Thank you and I love all of you",
" I love you",
" Tell my family that I love ya'll",
" I love you",
"  I thank the Lord for giving me my friends, for getting me the ones I love",
"  Melyssa, I love you girl",
"  Jack, Irene, Danny, Doreen, I love you guys",
"  I love you Melyssa, take care of that little monster for me",
"  I love ya'll and I'm gonna miss ya'll",
" I love you, and I'll see you in eternity",
" I'd like to say I love my mother, brother, sister, grandmother, cousins, and nieces, and my brothers and sisters I have never met",
" My love to my son, my daughter, Nancy, Kathy, Randy, and my future grandchildren",
"  I ask for forgiveness for all of the poison that I brought into the US, the country I love",
"  Sister Doris, mom, brothers, sister, dad; I love ya'll",
"   Ya'll know I love you, you too Ward",
"  Chris and David, I love you",
"  All my nieces and nephews, I love you all",
"  Yes sir, Ernest, Christopher, Ochente, Mary and Jennifer tell all the kids I love them and never forget",
"  My love always, I love you all",
"  I love you too",
"  I love you, I love you",
"  I love you Irene, I love you sis",
"  Thank you to my family, I love you",
"  I love you all",
" Irene, God bless you, I love you",
"   Yes, Love you mom, love you pop, love you Sara, and Amanda",
"  I love you dad, Devin, and Walt",
"  To my family, first and foremost - I love you all",
" I took his life for the love of a friend",
" I love you all",
" Jermaine, I love you too man",
"  To my family and my mother and my three precious daughters, I love you all",
"  Debbie, my Baby, I love you; do you know I love you",
"  Let my people know I love them",
"  I love you, I love my son, and I love my daughter",
"  Bruno, Chuckie, Juanita, Ray - I love you, all of you",
"  I love you forever",
"  Yes sir, to my family and children, I love you very much",
"  Dianne, Virginia, Toby and Irene I love all of you",
"  Please be strong and I love you all",
"  I love you Dianne, Mary Virginia",
" Kick the tires and light the fire, I am going home to see my son and my mom, I love you and God Bless you",
" I love you guys",
" I love you guys",
"  And to my family, and my loved ones - I am sorry for the pain for all those years and for putting you through all the things we had to go through",
"  Tammy, Irene, Betty, Dan Judy - I love you all",
"  To the victim's family, I am sorry you lost a brother, loved one, and friend",
"  To my family, I love you all",
"  I appreciate you all and love you",
"  I apologize that you lost a loved one this way",
"  I love you all",
"  I love you too",
"  Momma, I just want you to know I love you",
"  I want all of you to know I love you all",
"  I love you all",
"  I want each one of my loved ones to move on",
"  Let my son know I love him",
"  I love ya'll",
"  Honey, I love you",
"  Maria, Maria, I love you baby",
" I would like to thank all my friends and supporters, Anne West, who I love and respect",
" I love my children",
" I love my family",
"  To everybody on both sides of that wall--I want you to know I love you",
"  Tell my family I love them all and I will see them in Heaven",
"  I love my family",
" I love you",
" I love you",
" I love you",
"  I want to thank you all for being here and for your love and support",
"  I love you all",
"  Celina, I love you",
"  I love you all",
"  And if I see Amy on the other side, I will tell her how much you love and miss her and we will have a lot to talk about",
"  I love you all and I will see you on the other side",
" I love you all",
"  Man, I just want you to know how much I love them",
"  Let everybody know I love them (several names listed), Kevin - as well as everyone else in the family",
"  Tell them that I love them and stay strong",
"  I want you to know I love you; just stay strong and don't give up",
"  Let everybody know I love them",
"and love is unconditional, as Mama has always told us",
"  I love you",
" I would like to say I love the girls next to them",
"   Jack and Irene, I love you guys",
"  Tell my family I love them",
"  I love you",
"  I love you all",
"  Tell momma I love her",
" I did not kill your loved one, but I hope that one day you find out who did",
" I wish I could tell you the reason why, or give some kind of solace; you lost someone you love very much",
" And to you my family and friends, I love you dearly",
" Even though I die, that love for you will never die",
"  I love you all, all of you",
"  You know I love you",
"  I love you all",
"  I love you all very much",
"  I love you",
" To Edie, Tom, and and Carma - I love all you all",
"  I love you Margherita, Father Guido, and Father Angelo",
"  I love you all",
" I love you all",
" Give everybody my love",
" Give everybody my love, O",
" Mother, James, Justin, Corey, Brent, grand-babies and Daddy - I love you Pam",
" I love you Ashlee, Pammy and Irene",
"I love you all and for all your support",
"  I love you all",
"  I love you Mom and Dad, and all my family",
"  Jesus, thank you for your love and saving grace",
"  Thank you Jesus for the love you have shown me",
"  I love you and I will see all of you in Heaven",
"  I love you very much",
"  I love you",
" And to my family, I love you and I will see you all in Heaven",
"  I love you all",
"  I love you all",
"  I just wanted to say to all of those that have supported me over the years that I appreciate it and I love you",
"  And I just want to tell my mom that I love her and I will see her in Heaven",
"  I love you momma, and Misty and Annette, Brenda and Anthony - and all my friends and everybody that supported me",
"  I leave my love here; I am never going to stop loving you",
"  My love is going to stay here",
" I love you Earline and all of my friends that stood by me",
"  But thank you for your love and support; they have allowed me to do a lot more than I could have on my own",
"  I love you",
"  Andy, I love you man",
"  I love you all",
"  I love you all and I'll miss you all",
"  I want to say first that I love you Pam",
"  I love you, Ann, Jenny, Carla, Fran, Mom and Dad",
"  Thank you, baby girl - love you people",
"   I love you all",
"  Give them a hug and give them my love",
"  To my family and loved ones and friends, I thank all of you all for your support and I am sorry for the pain and hurt I have caused you",
"  I love you all and I will see you on the other side",
"  To my family and friends, I love you all",
"  I want to thank my family and friends; my family for all loving me and giving me so much love",
"  You, Brian's sister, thanks for your love --  it meant a lot",
"  To the moon and back -- I love you all",
"  I want Cindy to know that I know she is out there -- and Vicente Hernandez that I love them",
" I love you",
" Tell my kids I love them",
" I love you Gabby",
"  I love you all",
"  Tell Mama and the kids I love you; I love all of you",
"  I love you all",
" Connie, Nanny, Bea, Kathy and Richard - I love you all and I thank you all very much for supporting me with your love",
"  And to my family, know that I love every single one of you and pray that God gives you peace and strength",
"  I may not be with you in the physical, but by grace, my heart will be with you all and I know God loves every one of you all",
"  And thanks to Father (name unknown) and Guido Todeschini for your love and support",
"  I love you all",
"   I did have, but now I see my family here and everything - all I want to say is I love you all so much",
" I love you all so much",
"  I would like for Rosalyn's family and loved ones and my wife, Mary's, family to know that I am genuinely sorry for what I did",
"  As for my friends and family here - thanks for sticking with me and know that I love you and will take part of you with me",
"  I love you all",
"  I love you",
"  I love you",
" I love you",
" Big brother, you put up the best fight you could and I love you",
" I would like to thank Chaplain Lopez, and my witnesses for giving me their support and love",
" I want to tell my sons I love them; I have always loved them - they were my greatest gift from God",
" Blackwell that I love all of you and I am thankful for your support",
" My special angel, I love you",
" And I love you, Connie",
"   Tell Mama I love her and tell the kids I love them, too",
"   To the media, I would like for you to tell all the victims and their loved ones that I am truly, truly sorry for taking their loved ones' lives",
"  And to my Mom, I love you",
"  Let everyone know that I love them; this is not goodbye",
" That with my death, it will just remind them of their loved one, Mr",
"  Spoken: The statement I would like to make is to all my loved ones - and to the Abrahams and Williams families",
"  We came a long way through the tragedy - from hate to love and I would like to apologize for the pain I have caused all my families on both sides",
"  My brother Farooq, I love you my brother and send my love to all my family members",
"  I leave you with all my love and blessings",
"  Because I leave behind alot of people that loved me, that believe I could had been that someone",
"   Spoken: To all my family and friends, I want you to know that I love you very much",
"  I'll always remember you, and love you forever",
"  To my family and friends, Anne Dolatschko, Debbie Bilodeau, and the many supporters around the world, as well as my attorneys, Michael Charlton, who has always been there for me and done everything in their will and power to help me and stand by my side, I love you dearly, and you will always be in my heart forever",
"  I love all of you",
"  I love you Lundy, Levi, my dad",
"  To my family and friends, I love you and some day we will all be together again",
"  I would like to thank all my loved ones that are standing over there for all the kindness and support you have shown me over the years",
"  I love you all and appreciate all of you",
"  You won't be forgotten and there are a lot of people out there that love you",
"  Just give my love to everyone out there",
"  I love you all",
"  If I could change things I would, not for my sake but for all those who have loved me over the years, and for those who have forgiven me",
"  Thank you for all of your love and support",
"  You are all loved and respected",
" John 3:16:  For God so loved the world, that He gave his only begotten Son, that whosoever believeth in Him shall have everlasting life",
"  Forgive me; thank you for your love",
"  Wildflower:  I love you and will never forget you",
"   I am sorry for the pain: sorry for what I caused my friends, family and loved ones",
"  I love you all, Momma, Aunt Deidra, family and everybody",
"  I love you",
" To my sweet Claudia, I love you",
" I love you",
"  I thought about your loved one very much",
"   To my family, I thank you and love you for being there for me and supporting me",
"  I love you",
"  God bless you, I love you all, and I'm ready to go home",
"  Mom and Dad, I love you",
"  I love y'all and I want y'all to know that",
"  You know I love you and care for you",
"  Y'all take care and I love y'all",
"  I love y'all",
"  I love you",
"  I love you",
"  I pray that we all may learn to love and forgive so that we can have peace in the world",
"  It is with loving and forgiveness and living to learn to love and loving to live that we can learn the power of forgiveness and learn to live as brothers and sisters on this earth",
"  We should forgive and love and I do apologize with all my heart and soul and I love you and I know your spirit and God dwells within us and we are all one big family of humanity; we must all learn to love and live together",
"  I love my family and I know where I am going",
"  You all take care - Celina, David and tell Mama I love her, too",
"  Tom Crouch, and everybody, I love you",
"  I love them and I hurt for the the fact that they are going to be hurting",
" I loved Yolanda a lot",
" I thank all of you and I love all of you",
" Bye bye, I love you guys, don't worry about me",
"  I send love to my family and friends; my east side family and friends",
"  All I want to say, I love you all",
"  I love you, Colleen",
"  I love you",
"  If I lived to be a 100, the love we all share couldn't be more beautiful",
"7 tells us that God DID NOT instill in us the spirit of fear: but of power, love, and of sound mind",
"  I also want to thank you and Chief Neal, because of your actions, it shows me that you are human and can love, the same as I love my Club Brothers",
"  I really would have loved to have had the chance to take your lying ass to school, boy",
"  Because today your making my family and loved ones a victim just as you have cried to the world you were in this tragedy",
"  You know, the truth sets you free, and the truth is, if your loved one had acted with any professionalism at all, he would be alive today",
"  I love ya'll",
"  I'm deeply sorry for the loss of your loved one",
"  I'll start by saying I love all of you",
"  Tell my family I love y'all",
" Take care, love y'all",
" Tell Pat and them I love them",
" Help your sister, see ya later Pat, love ya Becca",
" Ursula, Manon, and Irene, I love y'all - take it easy",
" I love you",
" I love you all and thank you for being a part of my life",
" To my family I love each and every one of you",
" Know my love is always with you",
" I love each and everyone of you",
" You go back and tell your daughter I love her",
"   First, I would like to tell my family that I love them",
" I love y'all",
"  I love my sister, my friends, father",
" In the name of Jesus Christ I love you",
" Remember God is peace, God is love",
"  I love you, I love everyone, I go out with great love and respect",
"  (more mumbling)  I love you all",
"  God loves you all",
"  All that really matters is love",
"  There is no closure without love",
"  Our love is just like",
"  (unknown tongues)  I love the love in every man and child",
"  I am a minister of love",
"  I shed tears of love may they nourish everyone",
"  Brother Anderson, Kathy, I want you to know that I appreciate all these years that you have been coming to see me on death row and Daddy, I love you",
"  I appreciate y'all being here and being strong for me, and Mama, you know I love you, and I appreciate all of these visits, the letters and everything y'all have done for me",
"  I love y'all and you know, I want to apologize to y'all too for what I have done",
"  I love y'all and I won't say goodbye, I will say I will see you again",
"  I love you, Daddy",
" I got to go sister, I love you",
" You had some lovely girls and I am sorry",
" It would have been a lot harder without their love",
" I love you",
" I love y'all huh",
") I love you",
" I am sorry for your loss and hey, I love all y'all",
"   Mom, I just want y'all to know that I love you",
" I've got love for everybody",
" I love everybody and I want y'all to stay strong",
" Give my love to everybody",
" I love y'all",
" It is a blessing that there are people that they love so much but even more so, people that I love so much",
" For teaching me how to love, for all of the bad things you have taken out of my life",
"  I love you Heavenly Father, I love you Jesus",
" Mama, Adam, Mike, Sonny, Michelle, y'all know I love you",
" Tell everybody I said hi and that I love them and I will see them on the other side",
" I love y'all, stay sweet",
" I love ya",
"  I would like to extend my love to my family members and my relatives for all of the love and support you have showed me",
" I extend my special love to my daughter who I love greatly",
" I hope that you will always cherish the love and the strength that I have provided you",
" My love for you will remain with you winthin your heart and in part of your soul",
" As to all my brothers I love you all with all of my heart",
" But during your time of departure from this earth plane you will have to face the judgement of God for the lack of love you have shown my aunt and my cousins",
" As you know our parents brought us up to love one another no matter what",
" There was no love showed to my aunt or none of my cousins",
" To all the fellows on death row, I thank you for the love that you have shown me and for the strength that you provided me",
" May my love touch each one of you all's souls as I leave this body",
" I didn't kill your loved one",
" To my family and loved ones, I love you",
" I love you all",
"  Since I have already said all I need to say to all my loved ones, I'm not going to say anything to y'all at this time",
" Y'all know I love you and y'all know where we're at",
" There is nothing strange, love governs all events, what is (unintelligible), who is who was his mother and father, we extend my love to all my brothers and sister extend to life and my religion, it is Allah",
" So, I call on to all of my brothers and sisters and to members of the human race that still have some knowledge for what love divine love is",
" We extend our love to everyone who believes the faith of Islamic and chooses to love along with all their being",
" We extend our love to everybody",
" Extend my love to my divine sister",
" I love you all",
" I love all of you",
"  Know that I love all of you",
" I love the people, I love all of you for your blessing, strength, for your courage, for your dignity, the way you have come here tonight, and the way you have protested and kept this nation together",
"  I love you, Mr",
"  Ashanti Chimurenga, I love you for standing with me, my sister",
"  Reverend Al Sharpton, I love you, my brother",
"  Bianca Jagger, I love all of you",
" I love you, too, my brother",
" I love all of you",
" Maintain the love and unity in the community",
" And I love you, too, my brother",
"And to my family, I love you",
" Ah, you have been a blessing to me and I love you all and one day I will see y'all, so I hope y'all find y'all peace, comfort, and strength in Christ Jesus alone, because that's where it's at",
" I love you",
" I just want to testify to all of y'all that I have loved you",
" I appreciate your concern and genuine love for me",
" I love all of all",
" So for the life for which I live now in the flesh, I live by faith in the Son of God who loved me and gave himself for me",
" I love you, Annie",
" I love you, too",
" Don't give up, love you all, even the ones that are my enemies",
" Whatever the cost may be I love you",
" The supremacy of love over gifts: I Corinthians, Chapter 13: 4-8: Love is patient, love is kind, and is not jealous, love does not brag and is no arrogant, does not act unbecoming; it does not seek its own, is not provoked, does not take into account a wrong suffered, does not rejoice in unrighteousness, but rejoices with the truth; bears all things, believes all things, hopes all things, endures all things",
" Now abide faith, hope, love, these three: but the greatest of these is love",
" Spoken: Thank you, um, I anticipated that I would try to memorize and recite beatitudes New Testament, more or less, Luke's beatitudes, I should say, and a , a chapter on love in 1st Corinthians chapter 13, ah, I pretty much knew that I would not be able to memorize so much",
" I just want you to know that I love all of ya'll",
" Father, God, I just thank you for the time that you have given me on this earth, for having mercy on somebody like me for all the despicable thing's I've done in my life, Father, but you still with your love and your mercy reach down into my heart and changed it before it's too late",
" Just let them know that you love them, Father, and that You are the way",
" I love ya'll, ya'll take care",
"  Chaplain Brazzil recites written statement: To the Jones Family: Please accept my sincerest apology and regrets for what happened to your loved one",
" I can never find the words to express my love for all of you",
"  I'd like to send great love to all my family members, my supporters, my attorneys",
" I was sick, afraid, and looking for love in all the wrong ways",
" To my mother, I love you very much",
"  Dad, I love you both",
" I want to tell you all how much I love you all, how much I appreciate everything",
" I love you all and my family",
" If I am paying my debt to society, I am due a rebate and a refund, but I love you all and you all watch out for Mom and you all keep up, keep going",
" I love you, Gloria, always baby",
"  To my family, I love them",
" To Kami, I love you and will always be with you",
"  Like to tell my friends that I love them",
" Alison, I love you",
" You have my love",
" Remember this, if all you know is hatred, if all you know is blood love, you'll never be satisfied",
"  I want to start out by acknowledging the love that I've had in my family",
" I love everyone of them and have always been loved all of my life",
" I love all of you",
" That's really all I have to say except that I love my family",
" I love you booger bear",
" I love doodle bug, too",
" Father Mike, Father Walsh, love you all",
"   English: I love you",
" You are all my heart and soul and I love you so much",
" I just want to tell my family, everybody I love and I want you to know that I love you, and that God loves you too",
" I love ya'll",
" And to my family I would also like to extend to them the same apology for the pain and misery that I have put them through, and I love them dearly from the bottom of my heart, and one day I would like to see them on the other side",
" I would like to thank all of the men on Death Row who have showed me love throughout the years, but especially the last two or three weeks, and I hold nothing against no man",
"  Yes, I would like to give love to my mother, sisters and brothers and let them know that I am thinking of them right now and I want to thank God for giving me such a loving family",
" Yes, to my family, I love you",
" To my family: I love you",
" To my family: I love you",
" Sister, I love you and will be there with you, to help you",
"\" It goes: Tell the kids I love them and I’ll be there",
" First off, to the Rosenbaum family, to Cindy, to Scott, to everyone, I just want to say I have nothing but love for you",
" I have nothing but love for you",
" To my family, my soul beloved, you’re so beautiful, for all your love and support is just miraculous, everything that ya’ll have done",
" I send my love to Jay, to everyone",
" I have nothing but love for all of you",
" I love you",
" I love you",
" I love you all, too",
" I love you",
" As the ocean always returns to itself, love always returns to itself",
" And I do so with love on my lips",
" I just want to tell Catharina I love you",
" I love you",
" If I speak in the tongues of men and of angels, but have not love, I am only a resounding gong or a clanging cymbal",
" If I have the gift of prophecy and can fathom all mysteries and all knowledge, and if I have a faith that can move mountains, but have not love, I am nothing",
" If I give all I possess to the poor and surrender my body to the flames, but have not love, I gain nothing",
" Love is patient, love is kind",
" And now these three remain: faith, hope and love",
" But the greatest of these is love",
" I love you, Miguel",
" Tell my wife I love her",
" I love ya’ll",
" I love you all",
" I want to tell you folks there, of a… I have a love in my heart for you",
" To my friends, I’d like to say that I love you and I’m glad you’ve been a part of my life",
" I love all of you all",
" I love you all",
" I love you all",
" Give my love to my family",
" I love them",
" Baby, I love you",
" I love all of you very much",
" I love all of you very much",
" A lot of people view what is happening here as evil, but I want you to know that I found love and compassion here",
" I would like to see that wall that separates these groups here tonight brought down and that we would all have love and compassion for one another and that you all build a future for all of us",
" I love all…        ",
" I love my family and I want them to know that",
" They are without their loved ones",
" I love you all",
" Tell my brothers I love them",
" Jesus is all about love",
" I love you all",
" I would like to tell my family I love them and I hope to see them again soon",
" Thank you for the changes in my life you have given me, the love and closeness of my family, and my beautiful daughter",
" First, I would like to give praise to God for the love and grace that he has allowed for all of this to come together",
" Goodbye, sun, I love you",
" I love my parents",
" I have known the love of a good woman, my wife",
" I love and cherish my friends and family",
" Thank you for your love",
" I will always love you, Lynn",
" I will always love you",
" I would like to tell my family that I love them and always be strong and keep their heads up and keep faith in Jesus",
") I love my family, my mother",
" I want to let all of my people know and everybody who is here and supported me that I love them and wish them all the best",
" I love you, Mom -        ",
" I love you",
" I love you all",
" I love you all – (names of children) – Corey, Steve (garbled) – This is very important",
" I love ya’ll and I miss ya’ll",
" It was horrible and inexcusable for me to take the life of your loved one and to hurt so many mentally and physically",
" To all of my friends and family, I love you and I am going home -          ",
") Tell Mama I love her",
" I cannot find the words to express the sadness I feel for bringing this hurt and pain on my loved ones",
" I would like to tell my family I love them",
" I love you, Mom",
" There’s love and peace in Islam",
" I would like to tell my son, daughter and wife that I love them – Eden, if they want proof of them, give it to them",
" I love all of you, those I can and can’t see",
" With the love of Christ, my love for you is secure and I love you purely and wholeheartedly in the name of the Almighty God",
" I just love everybody, and that’s it",
" I love you all",
" I love you all",
" To my family who has kept me strong, I give my love",
" I just want to tell my family I love them, and I thank the Lord Jesus for giving me another chance and for saving me",
" I would like to tell my family I love them very dearly, and I know they love me",
" I love all of the people who supported me all of these years",
" I would like to tell the Merka family I love them, too",
" I love all of those on Death Row, and I will always hold them in my hands",
" Those who stood by me, I will always love you",
" When his attorney came into the witness room, he said, \"Tell Mom I love her",
"\" The attorney said back to him, \"I love you, too",
" To his family he added that he loved them all",
" He spoke to his family and said he would carry their love with him",
" I love my family",
" I love you all",
" Tell my mother I love her and continue on without me",
" Goodbye to my family; I love all of you, I’m sorry for the victim’s family",
" Give my love to everybody",
" \"I love you, Dad",
" Allow your holy spirit to flow as I know your love as been showered upon me",
" To my loved ones, I extend my undying love",
" To those close to me, know in your hearts I love you one and all",
"    I love you"];
